chore: comment linter output from CI

diff --git a/.github/workflows/build-lint-test.yml b/.github/workflows/build-lint-test.yml
--- a/.github/workflows/build-lint-test.yml
+++ b/.github/workflows/build-lint-test.yml
@@ -6,6 +6,14 @@ on: pull_request
 
 jobs:
   build-lint-test:
+    permissions:
+      # Default permissions (matching what would be set if the permissions section was missing at all)
+      contents: read
+      packages: read
+
+      # Need to add these 2 for eslint-annotate-action
+      pull-requests: write
+      checks: write
     runs-on: ubuntu-latest
 
     steps:
@@ -15,17 +23,44 @@ jobs:
       - name: Use Node.js v22
         uses: actions/setup-node@v4
         with:
-          node-version: "22.x"
+          node-version: "22.18.0"
           cache: "npm"
 
       - name: 📦 Install dependencies
         run: npm ci
 
       - name: 🔍 Run Solidity Linter
-        run: npm run lint:solidity
+        id: solhint
+        run: |
+          # Run lint and save output to a file
+          npm run lint:solidity > solhint-output.txt || echo "Lint failed" >> solhint-output.txt
+          cat solhint-output.txt
 
-      - name: 🎨 Run ESLint on JS/TS files
-        run: npm run lint
+      - name: 💬 Update PR Comment with Solhint Output
+        uses: actions/github-script@v7
+        with:
+          script: |
+            // Build the TS script
+            const { build } = require("unbuild");
+            await build("./.github/scripts", false, {entries: ["./parseSolhintOutput.ts"], outDir: "./"});
+            // Run the script
+            const { githubScript: parseSolhintOutput } = require("./.github/scripts/parseSolhintOutput.mjs");
+            await parseSolhintOutput({github, context});
+
+      - name: 💾 Save Code Linting Report JSON
+        run: npm run lint:report
+        continue-on-error: true
+
+      - name: 💬 Annotate Code Linting Results
+        uses: ataylorme/eslint-annotate-action@v3
+        with:
+          report-json: "packages/*/eslint_report.json"
+          only-pr-files: false
+          fail-on-warning: true
+          markdown-report-on-step-summary: true
+
+      # - name: 🎨 Run ESLint on JS/TS files
+      #   run: npm run lint
 
       # This will also generate the Typechain types and the files with the constants used by the Chai tests
       # The turbo configs in `turbo.json` is setup to run `npm run build` command first before `npm run build:js`.
